### ISSUE TITLE
放到云服务器上运行报错！

### ISSUE THREAD

**Issue by chenmg2020** [greyli/albumy#34]
Traceback (most recent call last):
  File "/root/Envs/albumy/lib/python3.7/site-packages/flask/cli.py", line 330, in __call__
    rv = self._load_unlocked()
  File "/root/Envs/albumy/lib/python3.7/site-packages/flask/cli.py", line 317, in _load_unlocked
    self._app = rv = self.loader()
  File "/root/Envs/albumy/lib/python3.7/site-packages/flask/cli.py", line 372, in load_app
    app = locate_app(self, import_name, name)
  File "/root/Envs/albumy/lib/python3.7/site-packages/flask/cli.py", line 246, in locate_app
    'Could not import "{name}".'.format(name=module_name)
flask.cli.NoAppException: Could not import "albumy".

**Comment by greyli** [comment]
麻烦提供完整的错误输出，以及出错前执行的相关命令。
