### ISSUE TITLE
新注册了一个账户但是无法收到验证邮件

### ISSUE THREAD

**Issue by Marssgon** [greyli/albumy#39]
请问是什么原因

**Comment by greyli** [comment]
你这样问问题没人能够回答。只有一句话让别人怎么判断？可能有几十种出错原因。下面是你在提这个问题时应该考虑或给出的信息：

- 有没有报错？有没有用搜索引擎搜索报错的关键信息？
- 使用的程序是线上示例还是自己手动运行的项目？
- 手动运行的话使用的是哪个 Python、Flask 版本和操作系统版本？
- 有没有设置邮箱服务器？
- 使用哪个邮箱服务器，服务器地址和密码是否正确？
- 是否改动过源码？

**Comment by Zepyhrus** [comment]
我有类似的问题，无法受到确认邮件。在添加了.env文件，配置smtp各环境变量后依然收不到，环境变量和之前自己写的mail的demo是一致的，后台报出问题是一样的（添加.env配置文件前后）：

`Exception in thread Thread-186:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/srobot/lib/python3.8/site-packages/flask_mail.py", line 492, in send
    message.send(connection)
  File "/home/ubuntu/anaconda3/envs/srobot/lib/python3.8/site-packages/flask_mail.py", line 427, in send
    connection.send(self)
  File "/home/ubuntu/anaconda3/envs/srobot/lib/python3.8/site-packages/flask_mail.py", line 188, in send
    self.host.sendmail(sanitize_address(envelope_from or message.sender),
  File "/home/ubuntu/anaconda3/envs/srobot/lib/python3.8/smtplib.py", line 854, in sendmail
    self.ehlo_or_helo_if_needed()
  File "/home/ubuntu/anaconda3/envs/srobot/lib/python3.8/smtplib.py", line 602, in ehlo_or_helo_if_needed
    if not (200 <= self.ehlo()[0] <= 299):
  File "/home/ubuntu/anaconda3/envs/srobot/lib/python3.8/smtplib.py", line 442, in ehlo
    self.putcmd(self.ehlo_msg, name or self.local_hostname)
  File "/home/ubuntu/anaconda3/envs/srobot/lib/python3.8/smtplib.py", line 369, in putcmd
    self.send(str)
  File "/home/ubuntu/anaconda3/envs/srobot/lib/python3.8/smtplib.py", line 361, in send
    raise SMTPServerDisconnected('please run connect() first')
smtplib.SMTPServerDisconnected: please run connect() first`

源代码变动仅添加了.env和一个static/jquery.min.js.map，是手动运行`flask forge`、`flask run`后的结果。

**Comment by Zepyhrus** [comment]
问题解决了，重启服务器后就可以正常收到邮件了（我以为开发环境修改环境变量后会自动重载的）。然后补充一个小问题，这里源码没有采用SendGrid的方式哈？

**Comment by greyli** [comment]
> 这里源码没有采用SendGrid的方式哈？

没有。这里的考虑是让示例程序尽可能通用，而不是绑定某一个第三方服务。
